### ISSUE TITLE
can't download sda/data/crema.dat file after install git lfs

### ISSUE THREAD

**Issue by peter064226** [Mombin/speech2vid#1]
Error downloading object: sda/data/crema.dat (bd81f9c): Smudge error: Error downloading sda/data/crema.dat (bd81f9c671f510c683c610c211522de1c5c675e77ffca659a7abc8d5535156a7): [bd81f9c671f510c683c610c211522de1c5c675e77ffca659a7abc8d5535156a7] Object does not exist on the server: [404] Object does not exist on the server

**Comment by Mombin** [comment]
hi, william.
I clone original code from [DinoMan](https://github.com/DinoMan/speech-driven-animation)
if you want to Download data file,
you should install git lfs and you can download that.
git lfs clone https://github.com/DinoMan/speech-driven-animation

if you do not download well, erase all original file and re-clone by git lfs

**Comment by peter064226** [comment]
thank u so much !!!
