### ISSUE TITLE
Model.zip need access 

### ISSUE THREAD

**Issue by LunaMK** [Mombin/speech2vid#3]
When I use predict.py to predict on a single image, I put pretrained.pt under ckpt to the root path and run:
`va = sda.VideoAnimator(gpu=0, model_path="data/grid.dat")`
there is an error occur:
`  va = sda.VideoAnimator(gpu=0, model_path="data/grid.dat")

2 frames
/usr/local/lib/python3.7/dist-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    775             "functionality.")
    776 
--> 777     magic_number = pickle_module.load(f, **pickle_load_args)
    778     if magic_number != MAGIC_NUMBER:
    779         raise RuntimeError("Invalid magic number; corrupt file?")

UnpicklingError: invalid load key, 'v'. `
###the solve : 
 download the model from [drive]( https://drive.google.com/file/d/1Aa1Jb0CGpiYXKHeTwpXAwcwu_yEqdkte/view?usp=sharing.)

**Comment by Mombin** [comment]
you can Download pretrained model through the link.
I try to access the link.
there is no problem and I can download it.

**Comment by LunaMK** [comment]
@Mombin 
I'm sorry I messed up the link
models in this [link](https://drive.google.com/drive/folders/1pJdsnknLmMLvA8RQIAV3AQH8vU0FeK16)
[image](https://user-images.githubusercontent.com/50502460/127135148-43de05df-341c-4332-bb35-2cd6f15277f4.png)
